name: Check Repository Structure

on:
  workflow_dispatch:

jobs:
  check-structure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Check directory structure
        run: |
          echo "Current directory: $(pwd)"
          echo "All files and directories:"
          ls -la
          echo "All directories (recursive):"
          find . -type d -not -path "*/node_modules/*" -not -path "*/\.*" | sort
          echo "All package.json files:"
          find . -name "package.json" | sort 